# Generated by Django 4.0.3 on 2022-05-24 18:07

import Patrols.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='title')),
                ('patrol_status', models.CharField(choices=[('Creation', 'Creation'), ('Active', 'Active'), ('Archive', 'Archive')], default='Creation', max_length=15, null=True, verbose_name='patrol status')),
                ('description', models.TextField(blank=True, max_length=1023, null=True, verbose_name='description')),
                ('time_created', models.DateTimeField(default=Patrols.models.current_time, verbose_name='time created')),
                ('time_updated_last', models.DateTimeField(default=Patrols.models.current_time, verbose_name='last updated')),
                ('location', models.CharField(choices=[('ד', 'ד'), ('ו', 'ו'), ('יא', 'יא'), ('נחל עשן', 'נחל עשן'), ('כלניות', 'כלניות'), ('סיגליות', 'סיגליות'), ('נווה זאב', 'נווה זאב'), ('נאות לון', 'נאות לון'), ('ט', 'ט'), ('ה', 'ה'), ('ב', 'ב'), ('א', 'א'), ('עיר עתיקה', 'עיר עתיקה'), ('נווה נוי', 'נווה נוי'), ('נחל בקע', 'נחל בקע'), ('עמק שרה', 'עמק שרה'), ('מ אזרחי', 'מ אזרחי'), ('ג', 'ג'), ('רמות', 'רמות'), ('רמות - קריית הייטק', 'רמות - קריית הייטק')], max_length=63)),
                ('date', models.DateField(default=Patrols.models.current_time, verbose_name='date')),
                ('start_time', models.TimeField(default=Patrols.models.current_time, verbose_name='start time')),
                ('end_time', models.TimeField(default=datetime.datetime(2022, 5, 24, 21, 7, 49, 943995, tzinfo=utc), verbose_name='end time')),
                ('priority', models.IntegerField(default=1, verbose_name='priority')),
                ('participants_needed', models.IntegerField(default=3, verbose_name='participants needed')),
                ('approved_reactions', models.ManyToManyField(blank=True, related_name='approved_reactions', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrols', to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(blank=True, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('users_participated', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
