# Generated by Django 4.0.4 on 2022-05-13 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 13, 17, 55, 38, 320451, tzinfo=utc), verbose_name='end time'),
        ),
    ]
