# Generated by Django 3.1.14 on 2022-05-12 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 12, 23, 31, 20, 942324, tzinfo=utc), verbose_name='end time'),
        ),
    ]
