# Generated by Django 4.0.4 on 2022-05-12 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0002_alter_patrol_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 12, 22, 45, 22, 303865, tzinfo=utc), verbose_name='end time'),
        ),
    ]
