# Generated by Django 3.1.14 on 2022-05-17 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0003_alter_patrol_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 18, 0, 53, 15, 699242, tzinfo=utc), verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
