# Generated by Django 3.1.14 on 2022-05-17 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0004_auto_20220518_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 18, 0, 53, 22, 925361, tzinfo=utc), verbose_name='end time'),
        ),
    ]
