<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-21 20:08
=======
# Generated by Django 4.0.3 on 2022-05-24 18:08
>>>>>>> e72f89392b4953f212253e21df6e554d34a4d407

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Patrols', '0007_alter_patrol_end_time_alter_patrol_id_and_more'),
=======
        ('Patrols', '0007_alter_patrol_end_time'),
>>>>>>> e72f89392b4953f212253e21df6e554d34a4d407
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
<<<<<<< HEAD
            field=models.TimeField(default=datetime.datetime(2022, 5, 21, 23, 8, 47, 750695, tzinfo=utc), verbose_name='end time'),
=======
            field=models.TimeField(default=datetime.datetime(2022, 5, 24, 21, 8, 28, 880733, tzinfo=utc), verbose_name='end time'),
>>>>>>> e72f89392b4953f212253e21df6e554d34a4d407
        ),
    ]
