# Generated by Django 4.0.3 on 2022-05-21 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0008_alter_patrol_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='description',
            field=models.TextField(blank=True, max_length=1023, null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 21, 23, 45, 15, 922001, tzinfo=utc), verbose_name='end time'),
        ),
    ]
