# Generated by Django 4.0.3 on 2022-05-21 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0009_alter_patrol_description_alter_patrol_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 21, 23, 45, 24, 646200, tzinfo=utc), verbose_name='end time'),
        ),
    ]
