# Generated by Django 4.0.3 on 2022-05-25 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0010_alter_patrol_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='update_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 25, 3, 25, 59, 869697, tzinfo=utc), verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='location',
            field=models.CharField(choices=[('ד', 'ד'), ('ו', 'ו'), ('יא', 'יא'), ('נחל עשן', 'נחל עשן'), ('סיגליות', 'סיגליות'), ('נווה זאב', 'נווה זאב'), ('נאות לון', 'נאות לון'), ('ט', 'ט'), ('ה', 'ה'), ('ב', 'ב'), ('א', 'א'), ('עיר עתיקה', 'עיר עתיקה'), ('נווה נוי', 'נווה נוי'), ('נחל בקע', 'נחל בקע'), ('מ אזרחי', 'מ אזרחי'), ('ג', 'ג'), ('רמות', 'רמות'), ('רמות - קריית הייטק', 'רמות - קריית הייטק')], default='א', max_length=63),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='participants_needed',
            field=models.IntegerField(default=2, verbose_name='participants needed'),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='priority',
            field=models.IntegerField(default=5, verbose_name='priority'),
        ),
    ]
