# Generated by Django 4.0.3 on 2022-05-25 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0011_patrol_update_priority_alter_patrol_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 25, 3, 38, 53, 343709, tzinfo=utc), verbose_name='end time'),
        ),
    ]
