# Generated by Django 4.0.3 on 2022-05-25 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patrols', '0012_alter_patrol_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 25, 4, 48, 34, 381855, tzinfo=utc), verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='priority',
            field=models.IntegerField(blank=True, default=5, verbose_name='priority'),
        ),
    ]
