# Generated by Django 4.0.4 on 2022-05-13 13:39

import Patrols.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='data')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=Patrols.models.current_time, null=True)),
                ('is_backup', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
    ]
