# Generated by Django 4.0.3 on 2022-05-21 20:08

import adminPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0002_auto_20220518_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=adminPage.models.current_time, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
