# Generated by Django 4.0.3 on 2022-05-24 16:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Parent', max_length=50)),
                ('ID_Number', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('Birthday', models.DateField(default=datetime.date.today)),
                ('First_Name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Last_Name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('City', models.CharField(default='Beer Sheba', max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Neighborhood', models.CharField(choices=[('ד', 'ד'), ('ו', 'ו'), ('יא', 'יא'), ('נחל עשן', 'נחל עשן'), ('כלניות', 'כלניות'), ('סיגליות', 'סיגליות'), ('נווה זאב', 'נווה זאב'), ('נאות לון', 'נאות לון'), ('ט', 'ט'), ('ה', 'ה'), ('ב', 'ב'), ('א', 'א'), ('עיר עתיקה', 'עיר עתיקה'), ('נווה נוי', 'נווה נוי'), ('נחל בקע', 'נחל בקע'), ('עמק שרה', 'עמק שרה'), ('מ אזרחי', 'מ אזרחי'), ('ג', 'ג'), ('רמות', 'רמות'), ('רמות - קריית הייטק', 'רמות - קריית הייטק')], max_length=63)),
                ('is_patrol_manager', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
