# Generated by Django 4.0.3 on 2022-05-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Neighborhood',
            field=models.CharField(choices=[('ד', 'ד'), ('ו', 'ו'), ('יא', 'יא'), ('נחל עשן', 'נחל עשן'), ('סיגליות', 'סיגליות'), ('נווה זאב', 'נווה זאב'), ('נאות לון', 'נאות לון'), ('ט', 'ט'), ('ה', 'ה'), ('ב', 'ב'), ('א', 'א'), ('עיר עתיקה', 'עיר עתיקה'), ('נווה נוי', 'נווה נוי'), ('נחל בקע', 'נחל בקע'), ('מ אזרחי', 'מ אזרחי'), ('ג', 'ג'), ('רמות', 'רמות'), ('רמות - קריית הייטק', 'רמות - קריית הייטק')], default='א', max_length=63),
        ),
    ]
