# Generated by Django 4.0.3 on 2022-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20220518_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Neighborhood',
            field=models.CharField(choices=[('ד', 'ד'), ('ו', 'ו'), ('יא', 'יא'), ('נחל עשן', 'נחל עשן'), ('כלניות', 'כלניות'), ('סיגליות', 'סיגליות'), ('נווה זאב', 'נווה זאב'), ('נאות לון', 'נאות לון'), ('ט', 'ט'), ('ה', 'ה'), ('ב', 'ב'), ('א', 'א'), ('עיר עתיקה', 'עיר עתיקה'), ('נווה נוי', 'נווה נוי'), ('נחל בקע', 'נחל בקע'), ('עמק שרה', 'עמק שרה'), ('מ אזרחי', 'מ אזרחי'), ('ג', 'ג'), ('רמות', 'רמות'), ('רמות - קריית הייטק', 'רמות - קריית הייטק')], max_length=63),
        ),
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
